In [43]:
import pandas as pd

In [44]:
# List of CSV files to read
csv1=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/domestic_visitors/domestic_visitors_2016.csv')
csv2=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/domestic_visitors/domestic_visitors_2017.csv')
csv3=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/domestic_visitors/domestic_visitors_2018.csv')
csv4=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/domestic_visitors/domestic_visitors_2019.csv')

In [45]:
# Concatenate the dataframes vertically
domestic_visitors = pd.concat([csv1,csv2,csv3,csv4], ignore_index=True)

In [46]:
domestic_visitors.tail(50)

              district        date      month  year visitors
1462         Vikarabad  01-11-2019   November  2019
1463         Vikarabad  01-12-2019   December  2019
1464       Wanaparthy   01-01-2019    January  2019    28131
1465       Wanaparthy   01-02-2019   February  2019    22342
1466       Wanaparthy   01-03-2019      March  2019    20050
1467       Wanaparthy   01-04-2019      April  2019    23749
1468       Wanaparthy   01-05-2019        May  2019    20010
1469       Wanaparthy   01-06-2019       June  2019    20050
1470       Wanaparthy   01-07-2019       July  2019    32625
1471       Wanaparthy   01-08-2019     August  2019    35860
1472       Wanaparthy   01-09-2019  September  2019    21375
1473       Wanaparthy   01-10-2019    October  2019    21234
1474       Wanaparthy   01-11-2019   November  2019    32657
1475       Wanaparthy   01-12-2019   December  2019    20556
1476  Warangal (Rural)  01-01-2019    January  2019    28700
1477  Warangal (Rural)  01-02-2019   February  2019    28800
1478  Warangal (Rural)  01-03-2019      March  2019    29000
1479  Warangal (Rural)  01-04-2019      April  2019    26900
1480  Warangal (Rural)  01-05-2019        May  2019    24900
1481  Warangal (Rural)  01-06-2019       June  2019    27100
1482  Warangal (Rural)  01-07-2019       July  2019    28600
1483  Warangal (Rural)  01-08-2019     August  2019    31600
1484  Warangal (Rural)  01-09-2019  September  2019    32600
1485  Warangal (Rural)  01-10-2019    October  2019    31100
1486  Warangal (Rural)  01-11-2019   November  2019    32150
1487  Warangal (Rural)  01-12-2019   December  2019    32050
1488  Warangal (Urban)  01-01-2019    January  2019   151545
1489  Warangal (Urban)  01-02-2019   February  2019   157755
1490  Warangal (Urban)  01-03-2019      March  2019   154305
1491  Warangal (Urban)  01-04-2019      April  2019   150425
1492  Warangal (Urban)  01-05-2019        May  2019   143230
1493  Warangal (Urban)  01-06-2019       June  2019   144400
1494  Warangal (Urban)  01-07-2019       July  2019   145440
1495  Warangal (Urban)  01-08-2019     August  2019   148030
1496  Warangal (Urban)  01-09-2019  September  2019   151070
1497  Warangal (Urban)  01-10-2019    October  2019   147450
1498  Warangal (Urban)  01-11-2019   November  2019   153880
1499  Warangal (Urban)  01-12-2019   December  2019   147700
1500   Yadadri Bhongir  01-01-2019    January  2019   479293
1501   Yadadri Bhongir  01-02-2019   February  2019    56525
1502   Yadadri Bhongir  01-03-2019      March  2019   481923
1503   Yadadri Bhongir  01-04-2019      April  2019   441150
1504   Yadadri Bhongir  01-05-2019        May  2019   345790
1505   Yadadri Bhongir  01-06-2019       June  2019   370566
1506   Yadadri Bhongir  01-07-2019       July  2019   332770
1507   Yadadri Bhongir  01-08-2019     August  2019   389010
1508   Yadadri Bhongir  01-09-2019  September  2019   366862
1509   Yadadri Bhongir  01-10-2019    October  2019   381860
1510   Yadadri Bhongir  01-11-2019   November  2019   365990
1511   Yadadri Bhongir  01-12-2019   December  2019   477635

In [47]:
domestic_visitors.isnull().sum()

district     0
date         0
month        0
year         0
visitors    30
dtype: int64

In [48]:
# Identify rows with null values
null_rows = domestic_visitors[domestic_visitors.isnull().any(axis=1)]

# Display the null rows
print(null_rows)

         district        date      month  year visitors
1044     Suryapet  01-01-2018    January  2018      NaN
1045     Suryapet  01-02-2018   February  2018      NaN
1046     Suryapet  01-03-2018      March  2018      NaN
1047     Suryapet  01-04-2018      April  2018      NaN
1048     Suryapet  01-05-2018        May  2018      NaN
1049     Suryapet  01-06-2018       June  2018      NaN
1050     Suryapet  01-07-2018       July  2018      NaN
1051     Suryapet  01-08-2018     August  2018      NaN
1052     Suryapet  01-09-2018  September  2018      NaN
1053     Suryapet  01-10-2018    October  2018      NaN
1054     Suryapet  01-11-2018   November  2018      NaN
1055     Suryapet  01-12-2018   December  2018      NaN
1344  Narayanapet  01-01-2019    January  2019      NaN
1345  Narayanapet  01-02-2019   February  2019      NaN
1346  Narayanapet  01-03-2019      March  2019      NaN
1347  Narayanapet  01-04-2019      April  2019      NaN
1348  Narayanapet  01-05-2019        May  2019      NaN
1349  Narayanapet  01-06-2019       June  2019      NaN
1440     Suryapet  01-01-2019    January  2019      NaN
1441     Suryapet  01-02-2019   February  2019      NaN
1442     Suryapet  01-03-2019      March  2019      NaN
1443     Suryapet  01-04-2019      April  2019      NaN
1444     Suryapet  01-05-2019        May  2019      NaN
1445     Suryapet  01-06-2019       June  2019      NaN
1446     Suryapet  01-07-2019       July  2019      NaN
1447     Suryapet  01-08-2019     August  2019      NaN
1448     Suryapet  01-09-2019  September  2019      NaN
1449     Suryapet  01-10-2019    October  2019      NaN
1450     Suryapet  01-11-2019   November  2019      NaN
1451     Suryapet  01-12-2019   December  2019      NaN

In [49]:
dm_visitors=domestic_visitors.copy()

In [50]:
dm_visitors.isnull().sum()

district     0
date         0
month        0
year         0
visitors    30
dtype: int64

In [51]:
dm_visitors=dm_visitors.dropna() # to remove null values

In [52]:
dm_visitors.isnull().sum()

district    0
date        0
month       0
year        0
visitors    0
dtype: int64

In [53]:
# to read foreign visters files 
csvf1=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/foreign_visitors/foreign_visitors_2016.csv')
csvf2=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/foreign_visitors/foreign_visitors_2017.csv')
csvf3=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/foreign_visitors/foreign_visitors_2018.csv')
csvf4=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/foreign_visitors/foreign_visitors_2019.csv')

In [54]:
# Concatenate the dataframes vertically
foreign_visitors = pd.concat([csvf1,csvf2,csvf3,csvf4], ignore_index=True)

In [55]:
foreign_visitors

             district        date      month  year visitors
0            Adilabad  01-01-2016    January  2016        2
1            Adilabad  01-02-2016   February  2016        0
2            Adilabad  01-03-2016      March  2016        2
3            Adilabad  01-04-2016      April  2016        0
4            Adilabad  01-05-2016        May  2016        0
...               ...         ...        ...   ...      ...
1507  Yadadri Bhongir  01-08-2019     August  2019        0
1508  Yadadri Bhongir  01-09-2019  September  2019        0
1509  Yadadri Bhongir  01-10-2019    October  2019        0
1510  Yadadri Bhongir  01-11-2019   November  2019        0
1511  Yadadri Bhongir  01-12-2019   December  2019        0

[1512 rows x 5 columns]

In [ ]:
foreign_visitors.tail(25)

In [57]:
foreign_visitors.isnull().sum()

district    0
date        0
month       0
year        0
visitors    0
dtype: int64

In [58]:
# exporting csvfiles 
dm_visitors.to_csv('domestic_visitors.csv', index=False)
foreign_visitors.to_csv('foreign_visitors.csv',index=False)